Support for translator 3.15.0
cqframework/cql-translation-service pull request #43
Opened 2024-09-17 18:22 UTC by elsaperelli

This PR bumps the version of the CQL translator from `3.7.1` to `3.15.0`. Release notes for `3.15.0` can be found [here](https://github.com/cqframework/clinical_quality_language/releases/tag/v3.15.0).

Summary of changes:
- In CQL translator version `3.10.0` (release notes [here](https://github.com/cqframework/clinical_quality_language/releases/tag/v3.10.0)), JUnit was updated to JUnit 5. I found [this page](https://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4) useful for the updates made in `FormatterResourceTest.java` and `TranslationResourceTest.java`.
    - Please make sure I didn't miss anything else.
- Due to upgrading JUnit I also had to upgrade jersey and jaxb-runtime.

2024-09-18 18:50 UTC, hossenlopp approved these changes
This looks good and tests out with retranslating measures.

2024-09-18 19:32 UTC, cmoesel requested changes
Thanks, Elsa!

I made one nit-picky comment about indented XML. I also noticed that this is out of sync with master; could you please merge or rebase to get in sync?

I assume that we will also want a new release (which would be release 2.5.0), so we will need to update the release number from 2.4.0 to 2.5.0 in:
* `pom.xml`
* `Dockerfile`
* `README.md` (two places, and also reflect the translator version 3.15.0 in the table)

We can either do that in this PR too (so we're ready to release right away) or we can put the 2.5.0 version bump in a separate PR following this one. I don't have a strong preference, so whatever is easier from your perspective.

Also -- don't worry about the failed GitHub Action for the Docker publish; that's actually probably a good thing (since we probably shouldn't push to DockerHub from forks).

2024-09-18 19:32 UTC, cmoesel commented on pom.xml
> +		</dependency>
These elements appear to be indented a good bit more than they should (if you don't see it, make sure you don't have "Hide whitespace" checked). I know it's kind of nit-picky, but could you fix the indentation so it's consistent with the rest?

2024-09-19 15:24 UTC, cmoesel approved these changes
Thanks, Elsa! I tested this manually as well as through Docker and all functionality is working as expected. And the JUnit 5 tests looks great. Thanks!

2024-09-19 15:26 UTC, hossenlopp approved these changes

2024-09-19 15:30 UTC, merged